controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: ClusterIP
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  config:
    allow-snippet-annotations: "true"
    annotations-risk-level: Critical
    enable-opentelemetry: "true"
    otlp-collector-host: "signoz-otel-collector.monitoring.svc.cluster.local"
    otlp-collector-port: "4317"
    otel-service-name: "ingress-nginx"
