name: Deploy monke-academy

on:
  push:
    branches: [prd]
    paths:
      - "hestia/monke-academy/site/**"
      - ".github/workflows/monke-academy-build.yml"
      - ".github/workflows/site-deploy.yml"
      - ".github/actions/**"
  pull_request:
    paths:
      - "hestia/monke-academy/site/**"
      - ".github/workflows/monke-academy-build.yml"
      - ".github/workflows/site-deploy.yml"
      - ".github/actions/**"
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/site-deploy.yml
    with:
      targets: >-
        [{"context": "hestia/monke-academy/site",
          "image": "monke-academy/site",
          "deployment": "monke-academy-site"}]
      purge_zone: monke.academy
    secrets: inherit
