cephClusterSpec:
  mon:
    count: 1
  mgr:
    count: 1

  dashboard:
    enabled: true
    ssl: false

  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "^(sda|sdb|nvme1n1)$"
    config:
      encryptedDevice: "true"

toolbox:
  enabled: true

cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: osd
      replicated:
        size: 2
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: false
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
