global:
  storageClass: local-path

clickhouse:
  replicaCount: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9363"
    prometheus.io/path: /metrics
  zookeeper:
    replicaCount: 1
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9141"
      prometheus.io/path: /metrics
  clickhouseOperator:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"
  persistence:
    size: 30Gi

schemaMigrator:
  enabled: true

queryService:
  replicaCount: 1

frontend:
  replicaCount: 1

otelCollector:
  replicaCount: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"

alertmanager:
  replicaCount: 1
