global:
  storageClass: local-path

clickhouse:
  replicaCount: 1
  zookeeper:
    replicaCount: 1
  persistence:
    size: 30Gi

schemaMigrator:
  enabled: true

queryService:
  replicaCount: 1

frontend:
  replicaCount: 1

otelCollector:
  replicaCount: 1

alertmanager:
  replicaCount: 1
