renovate:
  stage: sync
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api") && $RUN == "renovate"'
  image: renovate/renovate:44.79.1@sha256:53b0e93f79a5eaf0ee67320f3ced0a615a62476ca2f75591c808f5116183bd2a
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.vinnel.cloud/api/v4
    RENOVATE_TOKEN: "${CI_BOT_TOKEN}"
    RENOVATE_GITHUB_COM_TOKEN: "${GH_API_TOKEN}"
    RENOVATE_REPOSITORIES: vinnel-cloud/gaia
    RENOVATE_AUTODISCOVER: "false"
  script:
    - renovate
