renovate:
  stage: sync
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api") && $RUN == "renovate"'
  image: renovate/renovate:44.45.4@sha256:5ab76d9ffdd885d6dad7bd2aa9ae40242d3906c17c45f681425956b5950b42f7
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.vinnel.cloud/api/v4
    RENOVATE_TOKEN: "${CI_BOT_TOKEN}"
    RENOVATE_GITHUB_COM_TOKEN: "${GH_API_TOKEN}"
    RENOVATE_REPOSITORIES: vinnel-cloud/gaia
    RENOVATE_AUTODISCOVER: "false"
  script:
    - renovate
