#!/bin/bash
set -euo pipefail

for binary in code kubectl love starship; do
  if ! command -v "$binary" &>/dev/null; then
    echo "missing required binary: $binary" >&2
    exit 1
  fi
done

# root/ida passwords: randomly generated by Terraform, re-applied every pod
# start from the mounted secret (rootfs is ephemeral, so accounts and their
# passwords don't survive a restart otherwise). SSH itself stays key-only
# (PasswordAuthentication no) — these only gate sudo/su once you're in.
chpasswd <<< "root:$(cat /run/passwords/root)"
chpasswd <<< "ida:$(cat /run/passwords/ida)"

# the Projects PVC mounts under /home/ida, so the kubelet pre-creates the home
# root-owned; guarantee it exists and ida owns it before writing dotfiles.
install -d -m 755 -o ida -g ida /home/ida

install -d -m 700 -o ida -g ida /home/ida/.ssh
install -m 600 -o ida -g ida /run/authorized-keys/authorized_keys /home/ida/.ssh/authorized_keys

install -d -m 755 -o ida -g ida /home/ida/.config
install -m 644 -o ida -g ida /run/dotfiles/.zshrc /home/ida/.zshrc
install -m 644 -o ida -g ida /run/dotfiles/starship.toml /home/ida/.config/starship.toml

# admin kubeconfig -> ~ida/.kube/config so kubectl works by default. Non-fatal
# so a missing mount never blocks sshd.
install -d -m 700 -o ida -g ida /home/ida/.kube
install -m 600 -o ida -g ida /etc/momus-kube/config /home/ida/.kube/config 2>/dev/null \
  || echo "warning: kubeconfig not mounted at /etc/momus-kube/config" >&2

# hand the persistent workspace to ida so git clones can write. Non-fatal.
chown ida:ida /home/ida/Projects 2>/dev/null || true

# vscode-cli tunnel state PVC — same pre-created-root-owned situation as Projects.
chown ida:ida /home/ida/.vscode-cli 2>/dev/null || true

install -d -m 700 /etc/ssh/host_keys
[ -f /etc/ssh/host_keys/ssh_host_ed25519_key ] || ssh-keygen -q -t ed25519 -N "" -f /etc/ssh/host_keys/ssh_host_ed25519_key
[ -f /etc/ssh/host_keys/ssh_host_rsa_key ] || ssh-keygen -q -t rsa -b 4096 -N "" -f /etc/ssh/host_keys/ssh_host_rsa_key

install -d -m 755 /run/sshd
exec /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config
